-- SELECT department.department_id, department.name, role.title, role.salary, employee.first_name, employee.last_name
-- FROM department
-- LEFT JOIN role ON department.department_id = role.department_id
-- ORDER BY department.department_id;